In [12]:
#importing the required libraries
import keras
import tensorflow as tf
from keras.datasets import mnist
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.optimizers import SGD
from keras.utils import np_utils
from keras.utils.np_utils import to_categorical


In [13]:
#load the data
import tensorflow as tf
(x_train,y_train), (x_test, y_test)= tf.keras.datasets.mnist.load_data()

In [14]:
#Analyse the data
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)
x_train[0]

(60000, 28, 28) (60000,)
(10000, 28, 28) (10000,)


array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [15]:
print(x_train.shape)
print(x_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [16]:
#Reshaping Dataset
#Preprocess the data
num_classes=10
x_train=x_train.reshape(x_train.shape[0],28,28,1)
x_test=x_test.reshape(x_test.shape[0],28,28,1)
input_shape = (28,28,1)

In [18]:
#one hot encoding
#Convert class vectors to binary class matrices
y_train=keras.utils.np_utils.to_categorical(y_train,num_classes)
y_test=keras.utils.np_utils.to_categorical(y_test,num_classes)
x_train=x_train.astype('float32')
x_test=x_test.astype('float32')
x_train=x_train/255
x_test=x_test/255
print('x_train shape:',x_train.shape)
print(x_train.shape[0],'train samples')

x_train shape: (60000, 28, 28, 1)
60000 train samples


In [19]:
#Create the Model
batch_size=128
num_classes=10
epochs=20
model = Sequential()
model.add(Conv2D(32, kernel_size=(3,3),activation='relu',input_shape=input_shape))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(256,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes,activation='softmax'))

In [21]:
#compiling the model
model.compile(loss=keras.losses.categorical_crossentropy,optimizer=tf.keras.optimizers.Adadelta(),metrics=['accuracy'])

In [22]:
#train the model
hist = model.fit(x_train, y_train,batch_size=20,epochs=5,verbose=1,validation_data=(x_test, y_test))

Epoch 1/5
3000/3000 [==============================] - 219s 73ms/step - loss: 2.1771 - accuracy: 0.3394 - val_loss: 1.9714 - val_accuracy: 0.7192
Epoch 2/5
3000/3000 [==============================] - 211s 70ms/step - loss: 1.7134 - accuracy: 0.6242 - val_loss: 1.2861 - val_accuracy: 0.8024
Epoch 3/5
3000/3000 [==============================] - 208s 69ms/step - loss: 1.1315 - accuracy: 0.7134 - val_loss: 0.7738 - val_accuracy: 0.8375
Epoch 4/5
3000/3000 [==============================] - 210s 70ms/step - loss: 0.8241 - accuracy: 0.7625 - val_loss: 0.5742 - val_accuracy: 0.8589
Epoch 5/5
3000/3000 [==============================] - 211s 70ms/step - loss: 0.6946 - accuracy: 0.7888 - val_loss: 0.4852 - val_accuracy: 0.8740


In [23]:
#Observe the metrices
metrics = model.evaluate(x_test, y_test, verbose=0)
print("Metrics(Loss and Accuracy):")
print(metrics)

Metrics(Loss and Accuracy):
[0.48524171113967896, 0.8740000128746033]


In [25]:
#Test the model
prediction = model.predict(x_test[:4])
print(prediction)

[[5.98078885e-04 5.72901510e-04 1.72018609e-03 3.72925354e-03
  3.21394065e-03 8.67688272e-04 4.83752519e-04 9.71624434e-01
  4.64012427e-03 1.25497347e-02]
 [9.04008280e-03 8.06428678e-03 8.41161549e-01 7.67486617e-02
  8.46295079e-05 1.82363819e-02 2.32470967e-02 4.70476552e-05
  2.32539810e-02 1.16208874e-04]
 [2.25206348e-03 9.05286193e-01 1.57878380e-02 1.27998861e-02
  6.66152686e-03 5.69823198e-03 1.16989231e-02 9.32523701e-03
  2.29837373e-02 7.50641013e-03]
 [9.56700027e-01 1.10607998e-05 3.27006984e-03 2.98529863e-03
  5.44266833e-04 6.56919181e-03 2.48129759e-02 1.08106481e-03
  2.15184526e-03 1.87428982e-03]]


In [26]:
import numpy as np
print(np.argmax(prediction,axis=1))
print(y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [27]:
#observe the metrics
metrics = model.evaluate(x_test, y_test, verbose=0)

In [28]:
#predicting the output
predition=model.predict(x_test[:4])
print(prediction)

[[5.98078885e-04 5.72901510e-04 1.72018609e-03 3.72925354e-03
  3.21394065e-03 8.67688272e-04 4.83752519e-04 9.71624434e-01
  4.64012427e-03 1.25497347e-02]
 [9.04008280e-03 8.06428678e-03 8.41161549e-01 7.67486617e-02
  8.46295079e-05 1.82363819e-02 2.32470967e-02 4.70476552e-05
  2.32539810e-02 1.16208874e-04]
 [2.25206348e-03 9.05286193e-01 1.57878380e-02 1.27998861e-02
  6.66152686e-03 5.69823198e-03 1.16989231e-02 9.32523701e-03
  2.29837373e-02 7.50641013e-03]
 [9.56700027e-01 1.10607998e-05 3.27006984e-03 2.98529863e-03
  5.44266833e-04 6.56919181e-03 2.48129759e-02 1.08106481e-03
  2.15184526e-03 1.87428982e-03]]


In [29]:
#save the model

model.save('digit_classifier.h5')

In [32]:
!tar -zcvf digit_recognizer.tgz digit_classifier.h5

digit_classifier.h5


In [57]:
ls

digit_classifier.h5       digit_recognizer.tgz          my_model.tar.gz
digit_classifier_new.tgz  image_classification_new.tez


In [ ]:
#TEST WITH SAVED MODEL
#taking images as input
from keras.utils.image_utils import img_to_array
from tensorflow.keras.models import load_model
model = load_model('/content/digit_classifier.h5')
from PIL import Image
import numpy as np

img = Image.open('/content/sample4.png').convert("L")
img = img.resize((28,28))
im2arr = np.array(img)
im2arr = im2arr.reshape(1,28,28,1)

#display the image
import matplotlib.pyplot as plt
plt.imshow(img)

#predict the image
y_predict = model.predict(im2arr)
print(np.argmax(y_predict[0]))

In [35]:
pip install watson-machine-learning-client --upgrade

     |████████████████████████████████| 538 kB 2.8 MB/s eta 0:00:01�█████████████▎       | 409 kB 2.8 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [36]:
import ibm_watson_machine_learning
from ibm_watson_machine_learning import APIClient
wml_credentials = {
    "url": "https://us-south.ml.cloud.ibm.com",
    "apikey": "rtkpieDTx8O1oTlgf1qVDjOasiG3AlxzYwe2whx-PwPq"
}
client = APIClient(wml_credentials)

In [37]:
def guid_from_space_name(client, space_name):
    space = client.spaces.get_details()
    #print(space)
    return(next(item for item in space['resources'] if item['entity']["name"] == space_name)['metadata']['id'])

In [38]:
space_uid = guid_from_space_name(client, 'HDR')
print("Space UID = " + space_uid)

Space UID = 8ce5e61e-0934-4562-8a04-abe23199d3b0


In [39]:
client.set.default_space(space_uid)

'SUCCESS'

In [40]:
client.software_specifications.list()

-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
kernel-spark3.2-scala2.12      020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
tensorflow_2.4-py3.7-horovod   1092590a-307d-563d-9b62-4eb7d64b3f22  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
tensorflow_1.15-py3.6-ddl      111e41b3-de2d-5422-a4d6-bf776828c4b7  base
autoai-kb_rt22.2-py3.10        125b6d9

In [41]:
software_spec_uid = client.software_specifications.get_uid_by_name("tensorflow_rt22.1-py3.9")
software_spec_uid

'acd9c798-6974-5d2f-a657-ce06e986df4d'

In [42]:
model_details = client.repository.store_model(model='digit_classifier_new.tgz', meta_props={
    client.repository.ModelMetaNames.NAME:"CNN",
    client.repository.ModelMetaNames.TYPE:"tensorflow_2.7",
    client.repository.ModelMetaNames.SOFTWARE_SPEC_UID:software_spec_uid}
                                             )

model_id = client.repository.get_model_uid(model_details)

This method is deprecated, please use get_model_id()


/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/repository.py:1453: UserWarning: This method is deprecated, please use get_model_id()
  warn("This method is deprecated, please use get_model_id()")


In [43]:
model_id

'63dab09c-3df8-40f3-9750-7d9ba381002e'

In [44]:
client.repository.download(model_id, 'my_model.tar.gz')

Successfully saved model content to file: 'my_model.tar.gz'


'/home/wsuser/work/my_model.tar.gz'

In [45]:
from tensorflow.keras.models import load_model
from keras.preprocessing import image
from PIL import Image
import numpy as np

In [46]:
model=load_model("digit_classifier.h5")

In [49]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='vQ9nq7aQl3rzRaEKdwbQtEMhqFY650tUM8lLjl226vn8',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'testproject-donotdelete-pr-6q6kj6mib9ueve'
object_key = 'sample4.png'

streaming_body_4 = cos_client.get_object(Bucket=bucket, Key=object_key)['Body']

# Your data file was loaded into a botocore.response.StreamingBody object.
# Please read the documentation of ibm_boto3 and pandas to learn more about the possibilities to load the data.
# ibm_boto3 documentation: https://ibm.github.io/ibm-cos-sdk-python/
# pandas documentation: http://pandas.pydata.org/


In [51]:
img = Image.open(streaming_body_4).convert("L") # convert image to monochrome
img = img.resize( (28,28) ) # resizing

In [52]:
img

In [53]:
im2arr = np.array(img) #converting to image
im2arr = im2arr.reshape(1, 28, 28, 1) #reshaping according to our requirement

In [54]:
pred = model.predict(im2arr)
print(pred)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [55]:
print(np.argmax(pred, axis=1)) #print the label

[4]


In [1]:
pwd

'/home/wsuser/work'